version: '3'
services:
  todo-list-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/db_todolist
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mysql
    depends_on:
      - db
    command: ["sh", "-c", "sleep 30 && java -jar app.jar"]
  db:
    image: mysql:latest
    command: --bind-address=0.0.0.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=db_todolist
    ports:
      - "3306:3306"